name = "miniflare-typescript-esbuild-jest"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""

compatibility_date = "2021-11-15"
compatibility_flags = []

[durable_objects]
bindings = [
  { name = "COUNTER", class_name = "Counter" }
]

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist/src"
main = "./index.mjs"

[miniflare]
durable_objects_persist = true